<div class="jumbotron text-center">
    <h1>SMALL <span class="zf-green">INTERNET SHOP</span></h1>
</div><!-- /.jumbotron text-center -->

<div class="row">

    <?php foreach ($this->products as $product): ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title" id="panel-title-<?=$product->getId()?>"><?=$product->getName()?></h3>
            </div><!-- /.panel-heading -->
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>Article: </dt>
                    <dd class="article"></dd>
                    
                    <dt>Size: </dt>
                    <dd>
                        <form action="#" method="post" id="modificationBySize">
<?php foreach($product->getSizes() as $size): ?>
                            <input class="btn btn-default btn-xs" type="button" name="size" value="<?= $size; ?>" data-id="<?=$product->getId()?>" onclick="SelectModification(this);">
<?php endforeach; ?>
                        </form>
                    </dd>

                    <dt>Color: </dt>
                    <dd>
<?php foreach($product->getColors() as $color): ?>
                            <label class="radio-inline btn btn-default btn-xs" style="background-color: <?=$color;?>;">
                                <input type="radio" name="color" value="<?=$color;?>" data-id="<?=$product->getId()?>">
                            </label>
<?php endforeach; ?>
                    </dd>

                    <dt>Price: </dt>
                    <dd><?= $product->getPrice(); ?></dd>
                </dl>

                <p><a class="btn btn-primary pull-right" href="#">Go somewhere...</a></p>
            </div><!-- /.panel-body -->
        </div><!-- /.panel panel-default -->
    </div><!-- /.col-md-4 -->
<?php endforeach; ?>

</div><!-- /.row -->
