<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SMALL INTERNET SHOP')->setSeparator(' - ')->setAutoEscape(false); ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <?= $this->headLink(['rel'  => 'shortcut icon', 
                             'type' => 'image/vnd.microsoft.icon', 
                             'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css')); ?>
    </head>

    <body>

        <div class="container">

            <?= $this->content ?>

            <footer>
                <p>&copy; <?= date('Y') ?>. All rights reserved.</p>
            </footer>

        </div><!-- /.container -->

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <?= $this->headScript()->prependFile($this->basePath('js/javascript.js')); ?>

    </body>
</html>
